"use client"
import type {Metadata} from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import {CollapsibleTable} from "@/components/Table/Table";
import MUIDataTable from "mui-datatables";


const columns = ["Name", "Company", "City", "State"];

const data = [
    ["Joe James", "Test Corp", "Yonkers", "NY"],
    ["John Walsh", "Test Corp", "Hartford", "CT"],
    ["Bob Herm", "Test Corp", "Tampa", "FL"],
    ["James Houston", "Test Corp", "Dallas", "TX"],
];


const montserrat = Montserrat();

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={montserrat.className}>

        <MUIDataTable
            title={"Employee List"}
            data={data}
            columns={columns}

        />
        {children}
        </body>
        </html>
    );
}
