import type {Metadata} from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import {CollapsibleTable} from "@/components/Table/Table";

const montserrat = Montserrat();

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={montserrat.className}>
        <CollapsibleTable/>
        {children}
        </body>
        </html>
    );
}
